version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - mysql_db
    networks:
      - my_network

  # mysql_db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'flask_app_db'
  #     MYSQL_USER: 'flask_user'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'root_password'
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: